<?php

use App\Http\Controllers\Api\V1\Auth\LoginController;
use App\Http\Controllers\Api\V1\Auth\LogoutController;
use App\Http\Controllers\Api\V1\Auth\MeController;
use App\Http\Controllers\Api\V1\Auth\RegisterStudentController;
use App\Http\Controllers\Api\V1\Auth\RegisterTeacherController;
use App\Http\Controllers\Api\V1\Halaqas\CreateHalaqaController;
use App\Http\Controllers\Api\V1\Halaqas\GetHalaqaController;
use App\Http\Controllers\Api\V1\Halaqas\ListHalaqasController;
use App\Http\Controllers\Api\V1\Halaqas\SetHalaqaStatusController;
use App\Http\Controllers\Api\V1\Halaqas\UpdateHalaqaController;
use App\Http\Controllers\Api\V1\Memberships\AssignStudentToHalaqaController;
use App\Http\Controllers\Api\V1\Memberships\ListHalaqaStudentsController;
use App\Http\Controllers\Api\V1\Memberships\RemoveStudentFromHalaqaController;
use App\Http\Controllers\Api\V1\Memberships\UpdateMembershipController;
use App\Http\Controllers\Api\V1\Progress\FollowUpItemActionController;
use App\Http\Controllers\Api\V1\Progress\GetStudentAvailabilityController;
use App\Http\Controllers\Api\V1\Progress\GetStudentFollowUpPlanController;
use App\Http\Controllers\Api\V1\Progress\ListFollowUpItemsController;
use App\Http\Controllers\Api\V1\Progress\ListStudentMistakesController;
use App\Http\Controllers\Api\V1\Progress\ListStudentTrackingsController;
use App\Http\Controllers\Api\V1\Progress\UpdateStudentAvailabilityController;
use App\Http\Controllers\Api\V1\Progress\UpdateStudentFollowUpPlanController;
use App\Http\Controllers\Api\V1\Quran\QuranController;
use App\Http\Controllers\Api\V1\Realtime\AuthorizeRealtimeChannelController;
use App\Http\Controllers\Api\V1\Registrations\CancelRegistrationRequestController;
use App\Http\Controllers\Api\V1\Registrations\CreateRegistrationRequestController;
use App\Http\Controllers\Api\V1\Registrations\GetRegistrationRequestController;
use App\Http\Controllers\Api\V1\Registrations\ListRegistrationRequestsController;
use App\Http\Controllers\Api\V1\Registrations\RegistrationDecisionController;
use App\Http\Controllers\Api\V1\Reports\GetSessionReportController;
use App\Http\Controllers\Api\V1\Reports\ListStudentReportsController;
use App\Http\Controllers\Api\V1\Reports\SessionReportActionController;
use App\Http\Controllers\Api\V1\Reports\UpdateSessionReportController;
use App\Http\Controllers\Api\V1\Sessions\AcceptSessionController;
use App\Http\Controllers\Api\V1\Sessions\CancelSessionController;
use App\Http\Controllers\Api\V1\Sessions\CreateMistakeController;
use App\Http\Controllers\Api\V1\Sessions\CreateNoteController;
use App\Http\Controllers\Api\V1\Sessions\CreateSessionController;
use App\Http\Controllers\Api\V1\Sessions\CreateTaskController;
use App\Http\Controllers\Api\V1\Sessions\DeleteMistakeController;
use App\Http\Controllers\Api\V1\Sessions\DeleteNoteController;
use App\Http\Controllers\Api\V1\Sessions\EndSessionController;
use App\Http\Controllers\Api\V1\Sessions\GetEvaluationController;
use App\Http\Controllers\Api\V1\Sessions\GetMushafStateController;
use App\Http\Controllers\Api\V1\Sessions\GetRealtimeSessionController;
use App\Http\Controllers\Api\V1\Sessions\GetSessionController;
use App\Http\Controllers\Api\V1\Sessions\GetTaskController;
use App\Http\Controllers\Api\V1\Sessions\LeaveSessionController;
use App\Http\Controllers\Api\V1\Sessions\ListMistakesController;
use App\Http\Controllers\Api\V1\Sessions\ListNotesController;
use App\Http\Controllers\Api\V1\Sessions\ListTasksController;
use App\Http\Controllers\Api\V1\Sessions\ReconnectSessionController;
use App\Http\Controllers\Api\V1\Sessions\RejectSessionController;
use App\Http\Controllers\Api\V1\Sessions\SaveDraftController;
use App\Http\Controllers\Api\V1\Sessions\SaveMushafStateController;
use App\Http\Controllers\Api\V1\Sessions\UpdateMistakeController;
use App\Http\Controllers\Api\V1\Sessions\UpdateNoteController;
use App\Http\Controllers\Api\V1\Sessions\UpdateTaskController;
use App\Http\Controllers\Api\V1\Sessions\UpsertEvaluationController;
use App\Models\FollowUpItem;
use App\Models\HalaqaMembership;
use App\Models\LiveSession;
use App\Models\Mistake;
use App\Models\RegistrationRequest;
use App\Models\SessionTask;
use App\Models\TaskNote;
use App\Models\User;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::prefix('auth')->group(function (): void {
        Route::post('register/student', RegisterStudentController::class);
        Route::post('register/teacher', RegisterTeacherController::class);
        Route::post('login', LoginController::class);

        Route::middleware('auth:sanctum')->group(function (): void {
            Route::post('logout', LogoutController::class);
        });
    });

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('me', MeController::class);

        Route::get('halaqas', ListHalaqasController::class);
        Route::post('halaqas', CreateHalaqaController::class);
        Route::get('halaqas/{halaqa}', GetHalaqaController::class);
        Route::patch('halaqas/{halaqa}', UpdateHalaqaController::class);
        Route::post('halaqas/{halaqa}/activate', [SetHalaqaStatusController::class, 'activate']);
        Route::post('halaqas/{halaqa}/deactivate', [SetHalaqaStatusController::class, 'deactivate']);
        Route::get('halaqas/{halaqa}/students', ListHalaqaStudentsController::class);
        Route::post('halaqas/{halaqa}/students', AssignStudentToHalaqaController::class);
        Route::patch('halaqas/{halaqa}/memberships/{membership}', UpdateMembershipController::class);
        Route::delete('halaqas/{halaqa}/memberships/{membership}', RemoveStudentFromHalaqaController::class);

        Route::get('registration-requests', ListRegistrationRequestsController::class);
        Route::post('registration-requests', CreateRegistrationRequestController::class);
        Route::get('registration-requests/{registrationRequest}', GetRegistrationRequestController::class);
        Route::delete('registration-requests/{registrationRequest}', CancelRegistrationRequestController::class);
        Route::post('registration-requests/{registrationRequest}/accept', [RegistrationDecisionController::class, 'accept']);
        Route::post('registration-requests/{registrationRequest}/reject', [RegistrationDecisionController::class, 'reject']);
        Route::post('registration-requests/{registrationRequest}/request-completion', [RegistrationDecisionController::class, 'requestCompletion']);

        Route::model('membership', HalaqaMembership::class);
        Route::model('followUpItem', FollowUpItem::class);
        Route::model('registrationRequest', RegistrationRequest::class);
        Route::get('students/{student}/availability', GetStudentAvailabilityController::class);
        Route::put('students/{student}/availability', UpdateStudentAvailabilityController::class);
        Route::get('students/{student}/follow-up-plan', GetStudentFollowUpPlanController::class);
        Route::put('students/{student}/follow-up-plan', UpdateStudentFollowUpPlanController::class);
        Route::get('students/{student}/trackings', ListStudentTrackingsController::class);
        Route::get('students/{student}/mistakes', ListStudentMistakesController::class);
        Route::get('students/{student}/reports', ListStudentReportsController::class);
        Route::get('follow-up-items', ListFollowUpItemsController::class);
        Route::post('follow-up-items/{followUpItem}/complete', [FollowUpItemActionController::class, 'complete']);
        Route::post('follow-up-items/{followUpItem}/skip', [FollowUpItemActionController::class, 'skip']);
        Route::post('follow-up-items/{followUpItem}/reschedule', [FollowUpItemActionController::class, 'reschedule']);
        Route::model('student', User::class);
        Route::post('realtime/channels/authorize', AuthorizeRealtimeChannelController::class);
        Route::get('quran/surahs', [QuranController::class, 'surahs']);
        Route::get('quran/pages/{pageNumber}', [QuranController::class, 'page'])->whereNumber('pageNumber');
        Route::get('quran/ayahs/{ayahId}', [QuranController::class, 'ayah'])->whereNumber('ayahId');
        Route::post('sessions', CreateSessionController::class);
        Route::get('sessions/{session}', GetSessionController::class);
        Route::delete('sessions/{session}', CancelSessionController::class);
        Route::post('sessions/{session}/accept', AcceptSessionController::class);
        Route::post('sessions/{session}/reject', RejectSessionController::class);
        Route::post('sessions/{session}/leave', LeaveSessionController::class);
        Route::post('sessions/{session}/end', EndSessionController::class);
        Route::get('sessions/{session}/report', GetSessionReportController::class);
        Route::patch('sessions/{session}/report', UpdateSessionReportController::class);
        Route::post('sessions/{session}/report/teacher-approval', [SessionReportActionController::class, 'approve']);
        Route::post('sessions/{session}/report/student-acknowledgment', [SessionReportActionController::class, 'acknowledge']);
        Route::post('sessions/{session}/report/reopen', [SessionReportActionController::class, 'reopen']);
        Route::post('sessions/{session}/reconnect', ReconnectSessionController::class);
        Route::get('sessions/{session}/realtime', GetRealtimeSessionController::class);
        Route::get('sessions/{session}/mushaf-state', GetMushafStateController::class);
        Route::put('sessions/{session}/mushaf-state', SaveMushafStateController::class);
        Route::get('sessions/{session}/tasks', ListTasksController::class);
        Route::post('sessions/{session}/tasks', CreateTaskController::class);
        Route::get('sessions/{session}/tasks/{task}', GetTaskController::class);
        Route::patch('sessions/{session}/tasks/{task}', UpdateTaskController::class);
        Route::post('sessions/{session}/tasks/{task}/save-draft', SaveDraftController::class);
        Route::model('session', LiveSession::class);
        Route::get('sessions/{session}/tasks/{task}/mistakes', ListMistakesController::class);
        Route::post('sessions/{session}/tasks/{task}/mistakes', CreateMistakeController::class);
        Route::patch('sessions/{session}/tasks/{task}/mistakes/{mistake}', UpdateMistakeController::class);
        Route::delete('sessions/{session}/tasks/{task}/mistakes/{mistake}', DeleteMistakeController::class);
        Route::get('sessions/{session}/tasks/{task}/notes', ListNotesController::class);
        Route::post('sessions/{session}/tasks/{task}/notes', CreateNoteController::class);
        Route::patch('sessions/{session}/tasks/{task}/notes/{note}', UpdateNoteController::class);
        Route::delete('sessions/{session}/tasks/{task}/notes/{note}', DeleteNoteController::class);
        Route::get('sessions/{session}/tasks/{task}/evaluation', GetEvaluationController::class);
        Route::put('sessions/{session}/tasks/{task}/evaluation', UpsertEvaluationController::class);
        Route::model('task', SessionTask::class);
        Route::model('note', TaskNote::class);
        Route::model('mistake', Mistake::class);
    });
});
